# Generated by Django 3.2.3 on 2021-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_bookte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(db_column='title', max_length=20),
        ),
        migrations.AlterField(
            model_name='humaninfo',
            name='hcomment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
